version: '3'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_INITDB_DATABASE=bot
        - MONGO_INITDB_ROOT_USERNAME=bot
        - MONGO_INITDB_ROOT_PASSWORD=bot
    volumes:
        - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --auth # --quiet
    #command: mongod --auth --smallfiles --logpath=/dev/null # using auth